spring:
  application:
    name: demo-service
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: event
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    restart:
      enabled: true
my.property.name: Hello, World!

